name=Arduino_HardwareServo
version=0.0.1
author=Lucio Rossi, Giovanni Bruno, Arduino
maintainer=Arduino <info@arduino.cc>
sentence=Allows Arduino boards to control a variety of servo motors via hardware pwm.
paragraph=This library can control a great number of servos.
category=Device Control
url=https://github.com/arduino-libraries/Arduino_HardwareServo
architectures=zephyr,zephyr_main
